version: '3.7'
services:
  backend:
    build: ./backend
    image: ahsansabir30/socialmediab
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - PORT=${PORT}
  frontend:
    build: ./frontend
    image: ahsansabir30/socialmediaf
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    depends_on:
    - "backend"
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - "frontend"
volumes:
  db_volume: